-- Nelsoncon RSVP database bootstrap for Supabase/Postgres.
-- Safe to re-run: table, index, and policy creation are idempotent.

begin;

create table if not exists public.rsvps (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  full_name text not null,
  ticket_type text not null,
  source_page text
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'rsvps_full_name_not_blank'
      and conrelid = 'public.rsvps'::regclass
  ) then
    alter table public.rsvps
      add constraint rsvps_full_name_not_blank
      check (char_length(trim(full_name)) > 0);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'rsvps_ticket_type_not_blank'
      and conrelid = 'public.rsvps'::regclass
  ) then
    alter table public.rsvps
      add constraint rsvps_ticket_type_not_blank
      check (char_length(trim(ticket_type)) > 0);
  end if;
end
$$;

create index if not exists rsvps_created_at_idx on public.rsvps (created_at desc);

alter table public.rsvps enable row level security;

drop policy if exists "Allow anonymous RSVP insert" on public.rsvps;
create policy "Allow anonymous RSVP insert"
on public.rsvps
for insert
to anon
with check (true);

grant usage on schema public to anon;
grant insert on table public.rsvps to anon;
grant usage, select on sequence public.rsvps_id_seq to anon;

commit;
