-- Nelsoncon RSVP database bootstrap for Supabase/Postgres.
-- Safe to re-run: table, index, constraints, trigger, and policy are idempotent.

begin;

create table if not exists public.rsvps (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  full_name text not null,
  ticket_type text not null,
  source_page text
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'rsvps_full_name_not_blank'
      and conrelid = 'public.rsvps'::regclass
  ) then
    alter table public.rsvps
      add constraint rsvps_full_name_not_blank
      check (char_length(trim(full_name)) > 0);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'rsvps_full_name_format'
      and conrelid = 'public.rsvps'::regclass
  ) then
    alter table public.rsvps
      add constraint rsvps_full_name_format
      check (full_name ~ '^[A-Za-z0-9 .,''-]{2,80}$');
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'rsvps_ticket_type_not_blank'
      and conrelid = 'public.rsvps'::regclass
  ) then
    alter table public.rsvps
      add constraint rsvps_ticket_type_not_blank
      check (char_length(trim(ticket_type)) > 0);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'rsvps_ticket_type_allowed'
      and conrelid = 'public.rsvps'::regclass
  ) then
    alter table public.rsvps
      add constraint rsvps_ticket_type_allowed
      check (ticket_type in ('Normal Ticket', 'Private Room'));
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'rsvps_source_page_allowed'
      and conrelid = 'public.rsvps'::regclass
  ) then
    alter table public.rsvps
      add constraint rsvps_source_page_allowed
      check (
        source_page is null
        or source_page in ('/rsvp-payment.html', '/nelsoncon-website/rsvp-payment.html')
      );
  end if;
end
$$;

-- Enforce one RSVP per normalized full name (case/space-insensitive).
do $$
begin
  if to_regclass('public.rsvps_full_name_unique_norm_idx') is null then
    begin
      execute 'create unique index rsvps_full_name_unique_norm_idx on public.rsvps ((lower(trim(full_name))))';
    exception
      when unique_violation then
        raise notice 'Could not create unique index rsvps_full_name_unique_norm_idx because duplicates already exist. Clean duplicate names and re-run this script.';
    end;
  end if;
end
$$;

create or replace function public.prevent_duplicate_rsvp_name()
returns trigger
language plpgsql
as $$
begin
  if exists (
    select 1
    from public.rsvps existing
    where lower(trim(existing.full_name)) = lower(trim(new.full_name))
  ) then
    raise exception using
      errcode = '23505',
      message = 'duplicate RSVP for full_name';
  end if;

  return new;
end
$$;

drop trigger if exists rsvps_prevent_duplicate_name on public.rsvps;
create trigger rsvps_prevent_duplicate_name
before insert on public.rsvps
for each row
execute function public.prevent_duplicate_rsvp_name();

create index if not exists rsvps_created_at_idx on public.rsvps (created_at desc);

alter table public.rsvps enable row level security;

drop policy if exists "Allow anonymous RSVP insert" on public.rsvps;
create policy "Allow anonymous RSVP insert"
on public.rsvps
for insert
to anon
with check (
  char_length(trim(full_name)) between 2 and 80
  and full_name ~ '^[A-Za-z0-9 .,''-]{2,80}$'
  and ticket_type in ('Normal Ticket', 'Private Room')
  and (
    source_page is null
    or source_page in ('/rsvp-payment.html', '/nelsoncon-website/rsvp-payment.html')
  )
  and (
    select count(*)
    from public.rsvps recent
    where recent.created_at > now() - interval '1 minute'
  ) < 30
);

grant usage on schema public to anon;
grant insert on table public.rsvps to anon;
grant usage, select on sequence public.rsvps_id_seq to anon;

commit;
